-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.Investor (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  phone text,
  interest_calculation_type text NOT NULL DEFAULT 'annual_rate'::text,
  annual_interest_rate numeric,
  manual_interest_amount numeric,
  total_capital_contributed numeric DEFAULT 0,
  current_capital_balance numeric DEFAULT 0,
  status text DEFAULT 'Active'::text,
  organization_id uuid NOT NULL,
  CONSTRAINT Investor_pkey PRIMARY KEY (id),
  CONSTRAINT Investor_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.InvestorTransaction (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  investor_id uuid NOT NULL,
  investor_name text,
  type text NOT NULL,
  amount numeric NOT NULL,
  date date NOT NULL,
  reference text,
  notes text,
  organization_id uuid NOT NULL,
  CONSTRAINT InvestorTransaction_pkey PRIMARY KEY (id),
  CONSTRAINT investor_transactions_investor_id_fkey FOREIGN KEY (investor_id) REFERENCES public.Investor(id),
  CONSTRAINT InvestorTransaction_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  user_id uuid,
  action character varying NOT NULL,
  entity_type character varying,
  entity_id uuid,
  entity_name character varying,
  details jsonb,
  previous_values jsonb,
  new_values jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.borrowers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  unique_number text,
  first_name text NOT NULL,
  last_name text NOT NULL,
  full_name text,
  business text,
  gender text,
  phone text,
  mobile text,
  landline text,
  email text,
  address text,
  city text,
  zipcode text,
  country text,
  id_number text,
  status text DEFAULT 'Active'::text,
  import_created_date text,
  is_archived boolean DEFAULT false,
  archived_by text,
  archived_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid NOT NULL,
  notes text,
  CONSTRAINT borrowers_pkey PRIMARY KEY (id),
  CONSTRAINT borrowers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.expense_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  organization_id uuid NOT NULL,
  CONSTRAINT expense_types_pkey PRIMARY KEY (id),
  CONSTRAINT expense_types_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  type_id uuid NOT NULL,
  type_name text,
  amount numeric NOT NULL,
  description text,
  loan_id uuid,
  borrower_name text,
  organization_id uuid NOT NULL,
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.expense_types(id),
  CONSTRAINT expenses_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT expenses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.first_charge_holders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  name text NOT NULL,
  contact_email text,
  contact_phone text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT first_charge_holders_pkey PRIMARY KEY (id),
  CONSTRAINT first_charge_holders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  email text NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['Admin'::text, 'Manager'::text, 'Viewer'::text])),
  invited_by uuid NOT NULL,
  token text NOT NULL UNIQUE,
  expires_at timestamp with time zone NOT NULL,
  accepted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'accepted'::text, 'expired'::text, 'revoked'::text])),
  CONSTRAINT invitations_pkey PRIMARY KEY (id),
  CONSTRAINT invitations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.loan_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  interest_rate numeric NOT NULL,
  interest_type text NOT NULL,
  period text NOT NULL,
  interest_calculation_method text DEFAULT 'daily'::text,
  interest_alignment text DEFAULT 'period_based'::text,
  extend_for_full_period boolean DEFAULT false,
  interest_paid_in_advance boolean DEFAULT false,
  interest_only_period integer,
  created_at timestamp with time zone DEFAULT now(),
  max_amount integer,
  max_duration integer,
  min_amount integer,
  organization_id uuid NOT NULL,
  product_type text DEFAULT 'Standard'::text CHECK (product_type = ANY (ARRAY['Standard'::text, 'Fixed Charge'::text, 'Irregular Income'::text])),
  CONSTRAINT loan_products_pkey PRIMARY KEY (id),
  CONSTRAINT loan_products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.loan_properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  loan_id uuid NOT NULL,
  property_id uuid NOT NULL,
  charge_type text CHECK (charge_type = ANY (ARRAY['First Charge'::text, 'Second Charge'::text])),
  first_charge_holder_id uuid,
  first_charge_balance numeric,
  status text DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Removed'::text])),
  removed_date timestamp with time zone,
  removed_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loan_properties_pkey PRIMARY KEY (id),
  CONSTRAINT loan_properties_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT loan_properties_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT loan_properties_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT loan_properties_first_charge_holder_id_fkey FOREIGN KEY (first_charge_holder_id) REFERENCES public.first_charge_holders(id)
);
CREATE TABLE public.loans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_number text,
  borrower_id uuid NOT NULL,
  borrower_name text,
  product_id uuid NOT NULL,
  product_name text,
  principal_amount numeric NOT NULL,
  arrangement_fee numeric DEFAULT 0,
  exit_fee numeric DEFAULT 0,
  net_disbursed numeric,
  overpayment_credit numeric DEFAULT 0,
  interest_rate numeric,
  interest_type text,
  interest_only_period integer,
  duration integer NOT NULL,
  period text,
  start_date date NOT NULL,
  status text DEFAULT 'Live'::text,
  total_interest numeric DEFAULT 0,
  total_repayable numeric DEFAULT 0,
  principal_paid numeric DEFAULT 0,
  interest_paid numeric DEFAULT 0,
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_date timestamp with time zone,
  deleted_reason text,
  auto_extend boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  organization_id uuid NOT NULL,
  description text,
  product_type text DEFAULT 'Standard'::text CHECK (product_type = ANY (ARRAY['Standard'::text, 'Fixed Charge'::text, 'Irregular Income'::text])),
  monthly_charge numeric DEFAULT 0,
  total_charges numeric DEFAULT 0,
  charges_paid numeric DEFAULT 0,
  restructured_from_loan_id uuid,
  override_interest_rate boolean DEFAULT false,
  overridden_rate numeric,
  has_penalty_rate boolean DEFAULT false,
  penalty_rate numeric,
  penalty_rate_from date,
  CONSTRAINT loans_pkey PRIMARY KEY (id),
  CONSTRAINT loans_borrower_id_fkey FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id),
  CONSTRAINT loans_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.loan_products(id),
  CONSTRAINT loans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT loans_restructured_from_loan_id_fkey FOREIGN KEY (restructured_from_loan_id) REFERENCES public.loans(id)
);
CREATE TABLE public.organization_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['Admin'::text, 'Manager'::text, 'Viewer'::text])),
  invited_by uuid,
  invited_at timestamp with time zone DEFAULT now(),
  joined_at timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT organization_members_pkey PRIMARY KEY (id),
  CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT organization_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  logo_url text,
  settings jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  address text NOT NULL,
  city text,
  postcode text,
  country text DEFAULT 'UK'::text,
  property_type text CHECK (property_type = ANY (ARRAY['Residential'::text, 'Commercial'::text, 'Land'::text, 'Mixed Use'::text])),
  current_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT properties_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.repayment_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  installment_number integer NOT NULL,
  due_date date NOT NULL,
  principal_amount numeric NOT NULL,
  interest_amount numeric NOT NULL,
  total_due numeric NOT NULL,
  principal_paid numeric DEFAULT 0,
  interest_paid numeric DEFAULT 0,
  balance numeric,
  status text DEFAULT 'Pending'::text,
  calculation_days integer,
  calculation_principal_start numeric,
  calculation_method text,
  rolled_up_interest numeric,
  is_extension_period boolean DEFAULT false,
  organization_id uuid NOT NULL,
  charge_amount numeric DEFAULT 0,
  CONSTRAINT repayment_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT repayment_schedules_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT repayment_schedules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  loan_id uuid NOT NULL,
  borrower_id uuid,
  amount numeric NOT NULL,
  date date NOT NULL,
  type text NOT NULL,
  principal_applied numeric DEFAULT 0,
  interest_applied numeric DEFAULT 0,
  reference text,
  notes text,
  is_deleted boolean DEFAULT false,
  deleted_by text,
  deleted_date timestamp with time zone,
  deleted_reason text,
  organization_id uuid NOT NULL,
  fees_applied numeric DEFAULT 0,
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_loan_id_fkey FOREIGN KEY (loan_id) REFERENCES public.loans(id),
  CONSTRAINT transactions_borrower_id_fkey FOREIGN KEY (borrower_id) REFERENCES public.borrowers(id),
  CONSTRAINT transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  full_name text,
  avatar_url text,
  default_organization_id uuid,
  preferences jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT user_profiles_default_organization_id_fkey FOREIGN KEY (default_organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.value_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  property_id uuid NOT NULL,
  loan_property_id uuid,
  value_type text CHECK (value_type = ANY (ARRAY['Property Valuation'::text, 'First Charge Balance'::text])),
  value numeric NOT NULL,
  effective_date date NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT value_history_pkey PRIMARY KEY (id),
  CONSTRAINT value_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT value_history_property_id_fkey FOREIGN KEY (property_id) REFERENCES public.properties(id),
  CONSTRAINT value_history_loan_property_id_fkey FOREIGN KEY (loan_property_id) REFERENCES public.loan_properties(id),
  CONSTRAINT value_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);